on: push

jobs:
  compose:
    name: Build, run and test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up --abort-on-container-exit
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress artifacts
          path: |
            cypress/videos/
            cypress/snapshots/
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cypress JUnit Tests
          path: cypress/results/test-output-*.xml
          reporter: java-junit
